id: yukon_migrate_document
label: Yukon migrate Document Media Type
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Media
  - Ordered Migration
migration_group: legacy_media
source:
  plugin: yukon_migrate_file
  scheme: public
  file_type:
    - document
  batch_size: 200
  constants:
    source_base_path: 'https://yukon.ca/'
process:
  name: filename
  field_media_file/target_id:
    - plugin: migration_lookup
      migration: yukon_migrate_files__public
      source: fid
      no_stub: true
    - plugin: skip_on_empty
      method: row
  field_media_file/display:
    plugin: default_value
    default_value: 1
  field_document_name/value: field_document_name/0/value

  directory:
    plugin: migration_lookup
    migration: yukon_migrate_media_folders
    source: field_folder/0/tid
    no_stub: true

  filemime: filemime
  status: status
  created: timestamp
  changed: timestamp
  uuid: uuid
  # Todo: Replace this part with migration lookup after we migrate users.
  uid: uid
  langcode: source_language

destination:
  plugin: entity:media
  default_bundle: document

migration_dependencies:
  required:
    - yukon_migrate_files__public
