id: yukon_migrate_files__public
label: Yukon migrate Public files
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Files
  - Ordered Migration
migration_group: legacy_files
source:
  plugin: d7_file
  scheme: public
  batch_size: 200
  constants:
    source_base_path: 'https://yukon.ca/'
process:
  uuid: uuid
  filename: filename
  source_full_path:
    -
      plugin: concat
      delimiter: /
      source:
        - constants/source_base_path
        - filepath
    -
      plugin: urlencode
  uri:
    plugin: file_copy
    source:
      - '@source_full_path'
      - uri
    file_exists: 'use existing'
    move: false
  filemime: filemime
  status: status
  created: timestamp
  changed: timestamp
  # Todo: Replace this part with migration lookup after we migrate users.
  uid: uid
destination:
  plugin: entity:file
