<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_views_data_alter().
 */
function yukon_base_views_data_alter(array &$data) {
  $data['views']['exposed_form_selected_filters'] = [
    'title' => t('Exposed form - Selected filters'),
    'help' => '',
    'area' => [
      'id' => 'exposed_form_selected_filters',
    ],
  ];

  // Add custom field to file_usage table.
  $data['file_usage']['media_content_usage'] = [
    'title' => t('Content using this media'),
    'help' => t('Shows the content (nodes) that use this media entity.'),
    'field' => [
      'id' => 'media_content_usage',
    ],
  ];
}
