<?php

/**
 * @file
 * Yukon w3 migrate module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_theme().
 */
function yukon_w3_custom_theme() {
  return [
    'edit_language' => [
      'variables' => ['item' => NULL, 'language' => NULL],
      'template' => 'edit-language',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function yukon_w3_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $form['#attached']['library'][] = 'yukon_w3_custom/yukon_w3_custom.css';
  }
}

/**
 * Implements hook_views_data().
 */
function yukon_w3_custom_views_data() {
  $data = [];

  $data['views']['month_filter'] = [
    'title' => t('Month filter - Custom Filter'),
    'filter' => [
      'title' => t('Month filter - Custom Filter'),
      'field' => 'created',
      'id' => 'month_filter',
    ],
  ];

  return $data;
}

/**
 * Implements hook_page_attachments().
 */
function yukon_w3_custom_page_attachments(array &$page) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node)) {
    if (isset($node->field_collapsible_items)) {
      $items = $node->field_collapsible_items->getValue();
      foreach ($items as $item) {
        $p = Paragraph::load($item['target_id']);
        $chart = Paragraph::load($p->field_paragraphs->target_id);
        $chart_data[$chart->id()] = $chart->field_chart_data->value;

      }
      $page['#attached']['drupalSettings']['chart_data'] = $chart_data;
    }
  }
}
