#!/usr/bin/env bash

## Import config from a config directory.
##
## Usage: fin cim [params]

# shellcheck source=.docksal/scripts/common
. "${PROJECT_ROOT}/.docksal/scripts/common"

# Command entry point.
__init__() {
  # Start application.
  start_application

  fin drush cim "$@"
}

# Run the command.
__init__ "$@"
