#!/usr/bin/env bash

## Rebuild Cache.
##
## Usage: fin cr

# shellcheck source=.docksal/scripts/common
. "${PROJECT_ROOT}/.docksal/scripts/common"

# Command entry point.
__init__() {
  # Start application.
  start_application

  echo -e " ${GREEN_BG}Rebuilding Cache ...${DEFAULT}";
  fin drush cr "$@"
}

# Run the command.
__init__ "$@"
