#!/usr/bin/env bash

## Run gulp, the FE task runner.
##
## Usage: fin gulp [params]

# shellcheck source=.docksal/scripts/common
. "${PROJECT_ROOT}/.docksal/scripts/common"

THEME_DIR="docroot/themes/custom/${THEME_NAME}"

# Command entry point.
__init__() {
  # Start application.
  start_application

  # Run gulp.
  fin exec "cd $THEME_DIR && source ~/.profile && nvm install && yarn install --immutable && ./node_modules/gulp/bin/gulp.js" "$@"
}

# Run the command.
__init__ "$@"
