#!/usr/bin/env bash

## Run yarn, the node package manager.
##
## Usage: fin yarn [params]

# shellcheck source=.docksal/scripts/common
. "${PROJECT_ROOT}/.docksal/scripts/common"

# Variables.
THEME_DIR="docroot/themes/custom/${THEME_NAME}"

# Command entry point.
__init__() {
  # Start application.
  start_application

  fin exec "cd $THEME_DIR && nvm install && yarn" "$@"
}

# Run the command.
__init__ "$@"
